# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('url', models.URLField(blank=True, default=b'')),
                ('version', models.CharField(blank=True, max_length=64)),
                ('factory_type', models.CharField(choices=[(b'AutoPyFactory', b'AutoPyFactory'), (b'glideinWMS', b'glideinWMS')], default=b'AutoPyFactory', max_length=20)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_startup', models.DateTimeField(null=True)),
                ('last_cycle', models.PositiveIntegerField(default=0)),
                ('last_ncreated', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.CharField(max_length=80, unique=True)),
                ('cid', models.CharField(max_length=16)),
                ('state', models.CharField(choices=[(b'created', b'created'), (b'running', b'running'), (b'exiting', b'exiting'), (b'done', b'done'), (b'fault', b'fault')], default=b'created', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('result', models.SmallIntegerField(blank=True, default=-1)),
                ('flag', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-last_modified',),
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('msg', models.CharField(blank=True, max_length=255)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('resource', models.CharField(blank=True, max_length=128)),
                ('localqueue', models.CharField(blank=True, max_length=32)),
                ('batchqueue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kit.BatchQueue')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mon.Factory')),
            ],
            options={
                'ordering': ('name',),
                'get_latest_by': 'last_modified',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mon.Label'),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together=set([('fid', 'name')]),
        ),
    ]
