# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('state', models.CharField(blank=True, default=b'unknown', max_length=16)),
                ('comment', models.CharField(blank=True, default=b'', max_length=140)),
                ('type', models.CharField(blank=True, choices=[(b'ANALYSIS_QUEUE', b'ANALYSIS_QUEUE'), (b'PRODUCTION_QUEUE', b'PRODUCTION_QUEUE'), (b'SPECIAL_QUEUE', b'SPECIAL_QUEUE')], max_length=32, null=True)),
                ('control', models.CharField(blank=True, max_length=32, null=True)),
                ('timestamp', models.DateTimeField(editable=False, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('gocdbname', models.CharField(max_length=128, null=True, unique=True)),
                ('ssbname', models.CharField(max_length=128, null=True)),
                ('cloud', models.CharField(blank=True, choices=[(b'CA', b'CA'), (b'CERN', b'CERN'), (b'DE', b'DE'), (b'ES', b'ES'), (b'FR', b'FR'), (b'IT', b'IT'), (b'ND', b'ND'), (b'NL', b'NL'), (b'RU', b'RU'), (b'TW', b'TW'), (b'UK', b'UK'), (b'US', b'US')], max_length=8, null=True)),
                ('tier', models.CharField(blank=True, max_length=8, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WMSQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kit.Site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='batchqueue',
            name='wmsqueue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kit.WMSQueue'),
        ),
    ]
